apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: kubernetes
spec:
  filters:
    - dedot:
        de_dot_separator: "_"
        de_dot_nested: true
  match:
    - select: {}
  globalOutputRefs:
    - elasticsearch-kubernetes