apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      tolerations:
        - operator: Exists
      containers:
      - image: fluent/fluent-bit:1.4.4
        imagePullPolicy: IfNotPresent
        name: fluent-bit
        resources:
          limits:
            cpu: 200m
            memory: 100M
          requests:
            cpu: 100m
            memory: 50M
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/docker/containers
          name: varlibcontainers
          readOnly: true
        - mountPath: /var/log/
          name: varlogs
          readOnly: true
        - mountPath: /fluent-bit/etc/fluent-bit.conf
          name: config
          subPath: fluent-bit.conf
        - mountPath: /tail-db
          name: positiondb
        - mountPath: /buffers
          name: buffers
      restartPolicy: Always
      serviceAccountName: fluentd
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibcontainers
      - hostPath:
          path: /var/log
          type: ""
        name: varlogs
      - name: config
        secret:
          defaultMode: 420
          items:
          - key: fluent-bit.conf
            path: fluent-bit.conf
          secretName: fluentbit
      - hostPath:
          path: /var/log/fluentbit-pos
          type: ""
        name: positiondb
      - emptyDir: {}
        name: buffers
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate