apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  serviceName: ""
  replicas: 3
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - fluentd
              topologyKey: kubernetes.io/hostname
      serviceAccountName: fluentd
      tolerations:
      - operator: Exists
      containers:
      - name: fluentd
        image: quay.io/sighup/fluentd-elasticsearch
        args: ["-c", "/etc/tmp-conf/fluent.conf"]
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
        ports:
        - containerPort: 24231
          name: metrics
        - containerPort: 9880
          name: http-input
        - containerPort: 24240
          name: input
        livenessProbe:
          httpGet:
            # Use percent encoding for query param.
            # The value is {"log": "health check"}.
            # the endpoint itself results in a new fluentd
            # tag 'fluentd.pod-healthcheck'
            path: /fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D
            port: 9880
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 300m
            memory: 400Mi
        volumeMounts:
        - name: fluentd-conf
          mountPath: /etc/tmp-conf
        - name: fluentd-buffers
          mountPath: /buffers
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentd-conf
        configMap:
          name: fluentd-conf
  volumeClaimTemplates:
    - metadata:
        name: fluentd-buffers
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd
  name: fluentd
spec:
  ports:
  - name: metrics
    port: 24231
    protocol: TCP
  - name: input
    port: 24240
    protocol: TCP
  selector:
    app: fluentd
