# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      tolerations:
        - operator: Exists
      containers:
        - image: fluent/fluent-bit
          imagePullPolicy: IfNotPresent
          name: fluent-bit
          resources:
            limits:
              cpu: 200m
              memory: 100M
            requests:
              cpu: 100m
              memory: 50M
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 2020
              name: metrics
          volumeMounts:
            - mountPath: /var/lib/docker/containers
              name: varlibcontainers
              readOnly: true
            - mountPath: /var/log/
              name: varlogs
              readOnly: true
            - mountPath: /fluent-bit/etc/fluent-bit.conf
              name: config
              subPath: fluent-bit.conf
            - mountPath: /fluent-bit/etc/dedot.lua
              name: fluentbit-dedot-script
              subPath: dedot.lua
            - mountPath: /tail-db
              name: positiondb
            - mountPath: /buffers
              name: buffers
            - mountPath: /etc/machine-id
              name: etcmachineid
              readOnly: true
      restartPolicy: Always
      serviceAccountName: fluentd
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/machine-id
            type: File
          name: etcmachineid
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibcontainers
        - hostPath:
            path: /var/log
            type: ""
          name: varlogs
        - name: config
          secret:
            defaultMode: 420
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf
            secretName: fluentbit
        - name: fluentbit-dedot-script
          configMap:
            name: fluentbit-dedot-script
        - hostPath:
            path: /var/log/fluentbit-pos
            type: ""
          name: positiondb
        - emptyDir: {}
          name: buffers
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentbit
  name: fluentbit
spec:
  ports:
    - name: metrics
      port: 2020
      protocol: TCP
  selector:
    app: fluentbit