apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: systemd-etcd
spec:
  systemdTailers:
    - name: systemd-etcd-hosttailer
      disabled: false
      maxEntries: 100
      systemdFilter: etcd.service
