# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 9200
      protocol: TCP
      name: http
    - port: 9300
      name: node-to-node
      protocol: TCP
    - port: 9108
      name: metrics
      protocol: TCP
  clusterIP: None
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - elasticsearch
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sysctl
          image: alpine
          command: ['sh', '-c']
          args:
            - |
              sysctl -a
              MAX_MAP_COUNT=$(sysctl -a | grep max_map_count | cut -d " " -f3)
              if [ "$MAX_MAP_COUNT" -gt "262143" ]; then
                echo "Nothing to do, vm.max_map_count value is high enough"
              else
                echo "Changing vm.max_map_count value to 262144"
                sysctl -w vm.max_map_count=262144
                sysctl -p
              fi
              FILE_MAX=$(sysctl -a | grep file-max | cut -d " " -f3)
              if [ "$FILE_MAX" -gt "524287" ]; then
                echo "Nothing to do, fs.file-max value is high enough"
              else
                echo "Changing fs.file-max value to 524288"
                sysctl -w fs.file-max=524288
                sysctl -p
              fi
              chown -R 1000:1000 /usr/share/elasticsearch/data
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            privileged: true
      containers:
        - name: exporter
          image: justwatch/elasticsearch_exporter
          args:
          - '--es.uri=http://localhost:9200'
          - '--es.cluster_settings'
          - '--es.indices'
          - '--es.snapshots'
          - '--web.listen-address=:9108'
          ports:
            - containerPort: 9108
              name: metrics
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 200Mi
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch
          env:
            - name: network.host
              value: "0.0.0.0"
            - name: ES_JAVA_OPTS
              value: -Xms2G -Xmx2G
            - name: bootstrap.memory_lock
              value: "false"
            - name: cluster.name
              value: elasticsearch
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.initial_master_nodes
              value: "elasticsearch-0,"
            - name: discovery.seed_hosts
              value: "elasticsearch"
            - name: node.data
              value: "true"
            - name: node.ingest
              value: "true"
            - name: node.master
              value: "true"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: node-to-node
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          securityContext:
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            runAsUser: 1000
          readinessProbe:
            httpGet:
                path: /_cat/health
                port: http
            initialDelaySeconds: 40
            periodSeconds: 5
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /_cat/health
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 2000m
              memory: 4G
            requests:
              cpu: 1500m
              memory: 3G
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 30Gi
