apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: audit
spec:
  fileTailers:
    - name: audit
      disabled: false
      path: /var/log/kubernetes/kube-apiserver-audit.log
  workloadOverrides:
    nodeSelector:
      node.kubernetes.io/role: master
    tolerations:
      - operator: Exists
        effect: NoSchedule



