# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# Source: logging-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-operator
  namespace: logging
  labels:
    app.kubernetes.io/name: logging-operator
    helm.sh/chart: logging-operator-3.17.7
    app.kubernetes.io/instance: logging-operator
    app.kubernetes.io/version: "3.17.7"
    app.kubernetes.io/managed-by: Helm
---
# Source: logging-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: logging-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - nodes
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - use
  - watch
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - eventtailers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - eventtailers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - hosttailers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging-extensions.banzaicloud.io
  resources:
  - hosttailers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - clusterflows
  - clusteroutputs
  - flows
  - loggings
  - outputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - clusterflows/status
  - clusteroutputs/status
  - flows/status
  - loggings/status
  - outputs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
# Source: logging-operator/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logging-operator
  labels:
    app.kubernetes.io/name: logging-operator
    helm.sh/chart: logging-operator-3.17.7
    app.kubernetes.io/instance: logging-operator
    app.kubernetes.io/version: "3.17.7"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: logging-operator
    namespace: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-operator
---
# Source: logging-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: logging-operator
  namespace: logging
  labels:
    app.kubernetes.io/name: logging-operator
    helm.sh/chart: logging-operator-3.17.7
    app.kubernetes.io/instance: logging-operator
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: logging-operator
    app.kubernetes.io/instance: logging-operator
---
# Source: logging-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-operator
  namespace: logging
  labels:
    app.kubernetes.io/name: logging-operator
    helm.sh/chart: logging-operator-3.17.7
    app.kubernetes.io/instance: logging-operator
    app.kubernetes.io/version: "3.17.7"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: logging-operator
      app.kubernetes.io/instance: logging-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logging-operator
        app.kubernetes.io/instance: logging-operator
    spec:
      containers:
        - name: logging-operator
          image: "ghcr.io/banzaicloud/logging-operator"
          args:
            - -enable-leader-election=true
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 8080
      serviceAccountName: logging-operator
