# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - deploy.yaml
  - crds

images:
  - name: ghcr.io/banzaicloud/logging-operator
    newName: registry.sighup.io/fury/banzaicloud/logging-operator
    newTag: 3.17.7

