# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ism-policy-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: policy
              securityContext:
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
                runAsUser: 1000
              image: opensearchproject/opensearch-dashboards
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  cp /tmp/retention.json kubernetes-retention.json
                  sed -i 's/INDEXNAME/kubernetes/g' kubernetes-retention.json
                  curl -X PUT "http://opensearch-cluster-master:9200/_plugins/_ism/policies/kubernetes" -H "Content-Type: application/json" -d @./kubernetes-retention.json
                  cp /tmp/retention.json audit-retention.json
                  sed -i 's/INDEXNAME/audit/g' audit-retention.json
                  curl -X PUT "http://opensearch-cluster-master:9200/_plugins/_ism/policies/audit" -H "Content-Type: application/json" -d @./audit-retention.json
                  cp /tmp/retention.json events-retention.json
                  sed -i 's/INDEXNAME/events/g' events-retention.json
                  curl -X PUT "http://opensearch-cluster-master:9200/_plugins/_ism/policies/events" -H "Content-Type: application/json" -d @./events-retention.json
                  cp /tmp/retention.json systemd-retention.json
                  sed -i 's/INDEXNAME/systemd/g' systemd-retention.json
                  curl -X PUT "http://opensearch-cluster-master:9200/_plugins/_ism/policies/systemd" -H "Content-Type: application/json" -d @./systemd-retention.json
                  cp /tmp/retention.json ingress-controller-retention.json
                  sed -i 's/INDEXNAME/ingress-controller/g' ingress-controller-retention.json
                  curl -X PUT "http://opensearch-cluster-master:9200/_plugins/_ism/policies/ingress-controller" -H "Content-Type: application/json" -d @./ingress-controller-retention.json
                  cp /tmp/retention.json infra-retention.json
                  sed -i 's/INDEXNAME/infra/g' infra-retention.json
                  curl -X PUT "http://opensearch-cluster-master:9200/_plugins/_ism/policies/infra" -H "Content-Type: application/json" -d @./infra-retention.json
              volumeMounts:
                - name: config-volume
                  mountPath: /tmp
          volumes:
            - name: config-volume
              configMap:
                name: opensearch-ism-policies
          restartPolicy: OnFailure
  schedule: "0 * * * *"