# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
images:
- name: registry.sighup.io/fury/alpine
  newTag: "3.24"
- name: registry.sighup.io/fury/prometheuscommunity/elasticsearch-exporter
  newTag: v1.11.0
resources:
- deploy.yaml
- sm.yml
- rules.yml
- ism-policy-cronjob.yml
configMapGenerator:
- files:
  - configs/opensearch.yml
  name: opensearch-cluster-master-config
- files:
  - configs/retention.json
  name: opensearch-ism-policies
