# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

commonLabels:
  module.kfd.sighup.io/name: "logging"
  module.kfd.sighup.io/version: "v1.10.1"
  module.kfd.sighup.io/component: "opensearch"
  kfd.sighup.io/source: "kustomize"

images:
#  - name: justwatch/elasticsearch_exporter
#    newName: registry.sighup.io/fury/justwatch/elasticsearch_exporter
#    newTag: "1.1.0"
  - name: opensearchproject/opensearch
    newName: registry.sighup.io/fury/opensearchproject/opensearch
    newTag: "1.2.4"
  - name: alpine
    newName: registry.sighup.io/fury/alpine
    newTag: "3.14"

resources:
  - deploy.yaml
  - ns.yml
  - sm.yml
  - rules.yml

configMapGenerator:
  - name: opensearch-cluster-master-config
    files:
      - configs/opensearch.yml

secretGenerator:
  - name: opensearch-credentials
    envs:
      - opensearch-credentials.env
  - name: opensearch-internal-users
    files:
      - configs/internal_users.yml