[tasks.chart-versions]
description = "Show all Helm chart versions from opensearch/opensearch"
run = '''
helm repo add opensearch https://opensearch-project.github.io/helm-charts --force-update
helm repo update
helm search repo opensearch/opensearch --versions | head -11
'''

[tasks.upgrade]
description = "Upgrade the component with the specified chart version"
usage = '''
arg "<chart_version>" help="Chart version to use for the upgrade"
'''
run = '''
echo "Updating chart with version ${usage_chart_version}"

helm template opensearch opensearch/opensearch \
  --version ${usage_chart_version} \
  --values MAINTENANCE.values.yaml \
  -n logging > deploy.yaml
echo "Generated template in deploy.yaml"

yq -i 'select(.kind == "Service").spec.ports += {"name": "prom-metrics", "port": 9108}' deploy.yaml
echo "Added prom-metrics port to services for exporter sidecar"

mise run //:add-license
'''