# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curator
spec:
  schedule: "15 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: quay.io/sighup/curator
            command: ["curator"]
            args: ["--config", "/config/config.yml", "/config/action.yml"]
            env:
            - name: ES_HOST
              value: opensearch-cluster-master
            - name: UNIT
              value: days
            - name: UNIT_COUNT
              value: "30"
            envFrom:
              - secretRef:
                  name: opensearch-curator-credentials
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                cpu: 300m
                memory: 800Mi
            volumeMounts:
            - name: curator-config
              mountPath: /config
          restartPolicy: OnFailure
          volumes:
          - name: curator-config
            configMap:
              name: curator
