apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: audit
spec:
  filters:
    - dedot:
        de_dot_separator: "_"
        de_dot_nested: true
  match:
    - select:
        labels:
          app.kubernetes.io/instance: audit-host-tailer
  localOutputRefs:
    - elasticsearch-audit